# Generated by Django 5.0.6 on 2024-05-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('order_age', models.IntegerField()),
                ('package', models.BooleanField()),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Membership_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membership')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
