# Generated by Django 5.0.6 on 2024-06-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
