# Generated by Django 5.0.6 on 2024-06-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_is_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='IsDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='IsDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
