# Generated by Django 5.0.6 on 2024-06-01 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='menu/')),
                ('price', models.IntegerField()),
                ('IsDeleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.category')),
                ('owner_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('order_age', models.IntegerField()),
                ('package', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('Membership_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membership')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Order_amount',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('teenager', models.IntegerField(default=0)),
                ('adult', models.IntegerField(default=0)),
                ('elder', models.IntegerField(default=0)),
                ('aged', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('menu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menu')),
            ],
            options={
                'db_table': 'Order_amount',
            },
        ),
        migrations.CreateModel(
            name='Order_menu',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('Menu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.menu')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'Order_menu',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('IsDeleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.category')),
                ('order_menu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order_menu')),
            ],
        ),
    ]
