# Generated by Django 5.0.6 on 2024-06-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_optionchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='order_menu_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order_menu'),
        ),
    ]
