# Generated by Django 5.0.6 on 2024-06-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_createdat_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.category'),
        ),
    ]
