# Generated by Django 5.0.6 on 2024-06-02 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_options_order_menu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='name',
            new_name='option_name',
        ),
        migrations.RemoveField(
            model_name='options',
            name='cost',
        ),
    ]
