# Generated by Django 5.0.6 on 2024-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_membership_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_age',
            field=models.CharField(max_length=10),
        ),
    ]
