# Generated by Django 5.0.6 on 2024-06-03 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_category_owner_options_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='ID',
            new_name='option_ID',
        ),
    ]
