# Generated by Django 5.0.6 on 2024-06-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_id_options_option_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
    ]
