# Generated by Django 5.0.6 on 2024-06-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_category_table_alter_options_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='optionchoice',
            table='Option_choice',
        ),
    ]
